### ISSUE TITLE
File "download_shps.py", line 162, outshp.close() bug 

### ISSUE THREAD

**Issue by borisdev** [schmidtc/ACS_Tools#6]
```
Traceback (most recent call last):
  File "download_shps.py", line 173, in <module>
    fetch_and_merge_state_block_shapefiles(outname="blocks")
  File "download_shps.py", line 162, in fetch_and_merge_state_block_shapefiles
    outshp.close()
  File "/usr/local/lib/python2.7/dist-packages/pysal/core/IOHandlers/pyShpIO.py", line 187, in close
    self.dataObj.close()
  File "/usr/local/lib/python2.7/dist-packages/pysal/core/util/shapefile.py", line 385, in close
    self._shx.close(self.header)
  File "/usr/local/lib/python2.7/dist-packages/pysal/core/util/shapefile.py", line 525, in close
    self.fileObj.write(pack(fmt, *values))
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

**Comment by borisdev** [comment]
4GB LIMIT ON ALL SHAPEFILES

**Comment by schmidtc** [comment]
actually, I just noticed that last line, PySAL is using a signed Int which limits the shapefiles to 2GB (which according to ESRI is the limit, but I think that's more an issue with window's file systems and their 2gb filesize limit).  I'll update pysal to use unsigned, which should support 4gb.

**Comment by schmidtc** [comment]
Just checked the specification, it uses signed 32bit int.  So according to the spec the size is indeed limited 2 2GB.  GDAL/OGR was patched to allow 4gb shapefile by using unsigned ints (since negative files sizes don't make sense), however ArcMAP will not read files >2gb.
